



database:  
    host: localhost
    username: dave
    password: isnothere
    dbName: phoenix_portal
    
    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: dave
            password: isnothere
            dbName: phoenix_portal
    default: mysql
        
        
sms_server:
    host: 127.0.0.1
    port: 8086