



database:  
    host: localhost
    username: dave
    password: isnothere
    dbName: phoenix_portal
    
    
    datasource1:
        class: Gossamer\Tehuti\Database\RestDataSource

        credentials:
            baseUrl: http://phoenixdb.quantumunit.com
            format: json
            headers:
                authorization: tokengoeshere
                serverAuth: bQd18aba1df45jk7858c8ae88a57fa30
    
    mysql:
        class: 'Gossamer\Pesedget\Database\DBConnection'
        credentials:
            host: localhost
            username: dave
            password: isnothere
            dbName: phoenix_portal
    default: mysql
        
        
sms_server:
    host: 127.0.0.1
    port: 8086
