




tokens:
    component: "src/framework/components/tokens/config/routing.yml"
    

staff:
    component: "src/components/staff/config/routing.yml"    

traffic:
    component: "src/components/traffic/config/routing.yml"  
    
messaging:
    component: "src/components/messaging/config/routing.yml"  