

staff_newtoken:
    pattern: staff/newtoken
    listeners:
    #    - { 'event': 'component_request_start', 'listener': 'components\staff\listeners\StaffListener', 'datasource': 'mysql' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        view: Gossamer\Tehuti\Core\ServerView
        method: getNewToken
    
    
staff_updatepreferences:
    pattern: staff/updatepreferences
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        view: Gossamer\Tehuti\Core\ClientView
        method: updatePreferences    
        
staff_notify:  
    pattern: staff/notify
    listeners:
        - { 'event': 'component_request_start', 'listener': 'components\staff\listeners\SaveNotificationListener', 'datasource': 'mysql' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        view: Gossamer\Tehuti\Core\ClientView
        method: notify          
        
staff_connect: 
    pattern: staff/connect
    listeners:
       - { 'event': 'component_request_start', 'listener': 'components\staff\listeners\CheckStaffCredentialsListener' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        view: Gossamer\Tehuti\Core\ClientView
        method: connect       
        
staff_list_notifications: 
    pattern: staff/history
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        view: Gossamer\Tehuti\Core\ClientView
        method: listNotificationHistory   
        datasource: mysql