

staff_newtoken:
    pattern: staff/newtoken
    listeners:
        - { 'event': 'component_request_start', 'listener': 'components\staff\listeners\StaffListener', 'datasource': 'mysql' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: getNewToken
    
    
staff_updatepreferences:
    pattern: staff/updatepreferences
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: updatePreferences    
        
staff_notify:  
    pattern: staff/notify
    listeners:
       # - { 'event': 'request_start', 'listener': 'core\eventlisteners\LoadListListener', 'datasource': 'datasource1', 'class': 'components\geography\models\ProvinceModel', 'cacheKey': 'Provinces' }
    defaults:
        component: components\staff\StaffComponent
        controller: components\staff\controllers\StaffController
        model: components\staff\models\StaffModel
        method: notify          